version: '3.3'
services:
    clima:
        init: true
        container_name: clima
        image: code.bolha.one/bolha/clima:latest
        restart: unless-stopped
        environment:
#           WTH_API:
            WTH_LANG: pt
            MASTODON_TOKEN: <insira aqui>
            MASTODON_BASE_URL: <insira aqui>
            MASTODON_BIO_ONLINE: "Oi! Sou um robô que responde com o clima da cidade que você me perguntar. Basta me citar em uma mensagem contendo o nome do município desejado.\n\nExemplo: como está o clima em Recife?\nCaso a resposta mencione a cidade errada, informa o país: Recife, BR\n\n🟢 Status: estou aqui"
            MASTODON_BIO_OFFLINE: "Oi! Sou um robô que responde com o clima da cidade que você me perguntar. Basta me citar em uma mensagem contendo o nome do município desejado.\n\nExemplo: como está o clima em Recife?\nCaso a resposta mencione a cidade errada, informa o país: Recife, BR\n\n🔴 Status: volto já"
            UTW_NER_MODEL: pt_core_news_md
#           MAINTENANCE_STATUS="Desculpa {}, no momento estou em manutenção, mas logo retornarei!"
            API_TIMEOUT: 15
            PYTHONUNBUFFERED: 1